import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import SimpleBottomNavigation from "./components/SimpleBottomNavigation";
import { Box, Container, CssBaseline, ThemeProvider } from "@mui/material";
import ResponsiveAppBar from "./components/responsiveAppBar";
import CustomTheme from "./components/CustomTheme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Token Tide - Crowdfunding on Web3",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body className={inter.className} style={{ "background": "#fbf6f3" }}>
        <>
          <CssBaseline />
          <CustomTheme>
            <ResponsiveAppBar />
          </CustomTheme>
          <Container fixed>
            <Box sx={{ height: '100vh' }} >
              {children}
            </Box>
          </Container>
        </>
      </body>
    </html>
  );
}

